Fix namespace usage in console macros (#2892)
* Add regression test for #2896
* Fix namespace usage in console macros

This code did not work
```cpp
namespace foo::gazebo
{

class bar
{
public:
    void doSomething() {
        gzmsg << "doSomething" << std::endl;
    }
};

}  // foo::gazebo
```

because gzmsg resolves to (gazebo::common::Console::msg()).
It results in this error:
```
error: ‘foo::gazebo::common’ has not been declared
     #define gzmsg (gazebo::common::Console::msg())
```

Co-authored-by: Stefan Büttner <stefan.buettner@agile-robots.com>